apiVersion: apps/v1
kind: Deployment
metadata:
  name: socialsphere-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: your-dockerhub-username/socialsphere:latest
          ports:
            - containerPort: 4173
